### ISSUE TITLE
English Documentation?

### ISSUE THREAD

**Issue by DonaldTsang** [smolskig/api-magias-dnd#1]
This sounds pretty useful if it has documentation in English.

**Comment by smolskig** [comment]
Hey, the porpuse to create this is that we dont have a good portuguese D&D API, but the data font that the spells are collected have english content, so maybe i can go ahead with this and do a english version too.

Thanks for the message !!
Sorry for the late :D

**Comment by smolskig** [comment]
Hey bro, i just updated the API! now you can get your spells in english :D

**Comment by DonaldTsang** [comment]
thx
