### ISSUE TITLE
Onde esta a base de dados para a api ?

### ISSUE THREAD

**Issue by patrickelectric** [smolskig/api-magias-dnd#16]

**Comment by smolskig** [comment]
A fonte para essa base de dados vem daqui: https://dnd5spells.rpgist.net/pt-BR/spells
O site possui uma api mais completa pras spells, meu intuito era fazer um projeto básico, mais "direto ao ponto"

Fiz uma "copia" de todas as `Spells` deste site e coloquei num banco próprio (MongoDb Cloud), apenas pra estudo mesmo
